spring:
  application:
    name: backend
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID:dummy-id}
            clientSecret: ${GITHUB_CLIENT_SECRET:dummy-secret}
            scope: read:user,user:email,repo
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/rivetdeploy}
    username: ${SPRING_DATASOURCE_USERNAME:rivetdeploy}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true

server:
  port: 8081
